// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tides/api.proto

package tides

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RealtimeTidesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealtimeTidesRequest) Reset()         { *m = RealtimeTidesRequest{} }
func (m *RealtimeTidesRequest) String() string { return proto.CompactTextString(m) }
func (*RealtimeTidesRequest) ProtoMessage()    {}
func (*RealtimeTidesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bc507826c5c233, []int{0}
}

func (m *RealtimeTidesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealtimeTidesRequest.Unmarshal(m, b)
}
func (m *RealtimeTidesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealtimeTidesRequest.Marshal(b, m, deterministic)
}
func (m *RealtimeTidesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealtimeTidesRequest.Merge(m, src)
}
func (m *RealtimeTidesRequest) XXX_Size() int {
	return xxx_messageInfo_RealtimeTidesRequest.Size(m)
}
func (m *RealtimeTidesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RealtimeTidesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RealtimeTidesRequest proto.InternalMessageInfo

type RealtimeTidesResponse struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Meters               float64              `protobuf:"fixed64,2,opt,name=meters,proto3" json:"meters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RealtimeTidesResponse) Reset()         { *m = RealtimeTidesResponse{} }
func (m *RealtimeTidesResponse) String() string { return proto.CompactTextString(m) }
func (*RealtimeTidesResponse) ProtoMessage()    {}
func (*RealtimeTidesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bc507826c5c233, []int{1}
}

func (m *RealtimeTidesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealtimeTidesResponse.Unmarshal(m, b)
}
func (m *RealtimeTidesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealtimeTidesResponse.Marshal(b, m, deterministic)
}
func (m *RealtimeTidesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealtimeTidesResponse.Merge(m, src)
}
func (m *RealtimeTidesResponse) XXX_Size() int {
	return xxx_messageInfo_RealtimeTidesResponse.Size(m)
}
func (m *RealtimeTidesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RealtimeTidesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RealtimeTidesResponse proto.InternalMessageInfo

func (m *RealtimeTidesResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *RealtimeTidesResponse) GetMeters() float64 {
	if m != nil {
		return m.Meters
	}
	return 0
}

type PredictedTidesRequest struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PredictedTidesRequest) Reset()         { *m = PredictedTidesRequest{} }
func (m *PredictedTidesRequest) String() string { return proto.CompactTextString(m) }
func (*PredictedTidesRequest) ProtoMessage()    {}
func (*PredictedTidesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bc507826c5c233, []int{2}
}

func (m *PredictedTidesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictedTidesRequest.Unmarshal(m, b)
}
func (m *PredictedTidesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictedTidesRequest.Marshal(b, m, deterministic)
}
func (m *PredictedTidesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictedTidesRequest.Merge(m, src)
}
func (m *PredictedTidesRequest) XXX_Size() int {
	return xxx_messageInfo_PredictedTidesRequest.Size(m)
}
func (m *PredictedTidesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictedTidesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictedTidesRequest proto.InternalMessageInfo

func (m *PredictedTidesRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PredictedTidesResponse struct {
	Predictions          []*PredictedTidesResponse_Prediction `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *PredictedTidesResponse) Reset()         { *m = PredictedTidesResponse{} }
func (m *PredictedTidesResponse) String() string { return proto.CompactTextString(m) }
func (*PredictedTidesResponse) ProtoMessage()    {}
func (*PredictedTidesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bc507826c5c233, []int{3}
}

func (m *PredictedTidesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictedTidesResponse.Unmarshal(m, b)
}
func (m *PredictedTidesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictedTidesResponse.Marshal(b, m, deterministic)
}
func (m *PredictedTidesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictedTidesResponse.Merge(m, src)
}
func (m *PredictedTidesResponse) XXX_Size() int {
	return xxx_messageInfo_PredictedTidesResponse.Size(m)
}
func (m *PredictedTidesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictedTidesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictedTidesResponse proto.InternalMessageInfo

func (m *PredictedTidesResponse) GetPredictions() []*PredictedTidesResponse_Prediction {
	if m != nil {
		return m.Predictions
	}
	return nil
}

type PredictedTidesResponse_Prediction struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Meters               float64              `protobuf:"fixed64,2,opt,name=meters,proto3" json:"meters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PredictedTidesResponse_Prediction) Reset()         { *m = PredictedTidesResponse_Prediction{} }
func (m *PredictedTidesResponse_Prediction) String() string { return proto.CompactTextString(m) }
func (*PredictedTidesResponse_Prediction) ProtoMessage()    {}
func (*PredictedTidesResponse_Prediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bc507826c5c233, []int{3, 0}
}

func (m *PredictedTidesResponse_Prediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictedTidesResponse_Prediction.Unmarshal(m, b)
}
func (m *PredictedTidesResponse_Prediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictedTidesResponse_Prediction.Marshal(b, m, deterministic)
}
func (m *PredictedTidesResponse_Prediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictedTidesResponse_Prediction.Merge(m, src)
}
func (m *PredictedTidesResponse_Prediction) XXX_Size() int {
	return xxx_messageInfo_PredictedTidesResponse_Prediction.Size(m)
}
func (m *PredictedTidesResponse_Prediction) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictedTidesResponse_Prediction.DiscardUnknown(m)
}

var xxx_messageInfo_PredictedTidesResponse_Prediction proto.InternalMessageInfo

func (m *PredictedTidesResponse_Prediction) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PredictedTidesResponse_Prediction) GetMeters() float64 {
	if m != nil {
		return m.Meters
	}
	return 0
}

func init() {
	proto.RegisterType((*RealtimeTidesRequest)(nil), "jimmyau.tides.RealtimeTidesRequest")
	proto.RegisterType((*RealtimeTidesResponse)(nil), "jimmyau.tides.RealtimeTidesResponse")
	proto.RegisterType((*PredictedTidesRequest)(nil), "jimmyau.tides.PredictedTidesRequest")
	proto.RegisterType((*PredictedTidesResponse)(nil), "jimmyau.tides.PredictedTidesResponse")
	proto.RegisterType((*PredictedTidesResponse_Prediction)(nil), "jimmyau.tides.PredictedTidesResponse.Prediction")
}

func init() { proto.RegisterFile("tides/api.proto", fileDescriptor_34bc507826c5c233) }

var fileDescriptor_34bc507826c5c233 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x89, 0xca, 0x90, 0x3b, 0xa7, 0x18, 0xdc, 0x18, 0x7d, 0x71, 0x74, 0x13, 0xf6, 0x62,
	0x2a, 0xf3, 0x13, 0x38, 0x04, 0x5f, 0x47, 0xdc, 0xd3, 0x40, 0xa4, 0x7f, 0xae, 0x35, 0x63, 0x59,
	0x62, 0x93, 0x08, 0x7e, 0x3d, 0xdf, 0xfc, 0x56, 0xd2, 0x74, 0xc3, 0x75, 0x0c, 0xff, 0x80, 0x8f,
	0x3d, 0xe7, 0xdc, 0x7b, 0x6e, 0x7f, 0x2d, 0x9c, 0x58, 0x91, 0xa1, 0x89, 0x62, 0x2d, 0x98, 0x2e,
	0x94, 0x55, 0xb4, 0x35, 0x17, 0x52, 0xbe, 0xc5, 0x8e, 0x79, 0x23, 0x38, 0xcf, 0x95, 0xca, 0x17,
	0x18, 0x79, 0x33, 0x71, 0x4f, 0x91, 0x15, 0x12, 0x8d, 0x8d, 0xa5, 0xae, 0xf2, 0x61, 0x07, 0xce,
	0x38, 0xc6, 0x8b, 0x52, 0x9e, 0x96, 0x13, 0x1c, 0x5f, 0x1c, 0x1a, 0x1b, 0x3e, 0x42, 0x7b, 0x4b,
	0x37, 0x5a, 0x2d, 0x0d, 0x52, 0x06, 0x07, 0xa5, 0xd8, 0x25, 0x3d, 0x32, 0x6c, 0x8e, 0x02, 0x56,
	0x15, 0xb0, 0x75, 0x01, 0x9b, 0xae, 0x0b, 0xb8, 0xcf, 0xd1, 0x0e, 0x34, 0x24, 0x5a, 0x2c, 0x4c,
	0x77, 0xaf, 0x47, 0x86, 0x84, 0xaf, 0x9e, 0xc2, 0x3b, 0x68, 0x4f, 0x0a, 0xcc, 0x44, 0x6a, 0x31,
	0xdb, 0x6c, 0xfe, 0x6b, 0x41, 0xf8, 0x4e, 0xa0, 0xb3, 0xbd, 0x69, 0x75, 0x2b, 0x87, 0xa6, 0xae,
	0x1c, 0xa1, 0x96, 0xa6, 0x4b, 0x7a, 0xfb, 0xc3, 0xe6, 0xe8, 0x8a, 0xd5, 0x10, 0xb1, 0xdd, 0xb3,
	0x6b, 0x59, 0xa8, 0x25, 0xdf, 0x5c, 0x12, 0x4c, 0x01, 0xbe, 0xac, 0xff, 0xa2, 0x31, 0xfa, 0x20,
	0x70, 0xe4, 0xfb, 0xef, 0xb1, 0x78, 0x15, 0x29, 0xd2, 0x19, 0xb4, 0x6a, 0xfc, 0x69, 0x7f, 0xeb,
	0xec, 0x5d, 0x5f, 0x2d, 0x18, 0x7c, 0x1f, 0x5a, 0x61, 0x79, 0x80, 0xe3, 0xfa, 0x4b, 0xd3, 0xc1,
	0x0f, 0x4c, 0xaa, 0xed, 0x17, 0xbf, 0x22, 0x37, 0xbe, 0x85, 0xd3, 0x54, 0xc9, 0x7a, 0x76, 0x7c,
	0x78, 0xa3, 0xc5, 0xa4, 0xa4, 0x32, 0x21, 0xb3, 0x7e, 0x2e, 0xec, 0xb3, 0x4b, 0x58, 0xaa, 0x64,
	0x34, 0x9f, 0x27, 0x2e, 0x71, 0x99, 0xa8, 0xfe, 0x50, 0x73, 0x99, 0xab, 0xc8, 0x0f, 0x24, 0x0d,
	0x2f, 0x5c, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x50, 0xa7, 0x2a, 0xe2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TidesServiceClient is the client API for TidesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TidesServiceClient interface {
	RealtimeTides(ctx context.Context, in *RealtimeTidesRequest, opts ...grpc.CallOption) (*RealtimeTidesResponse, error)
	PredictedTides(ctx context.Context, in *PredictedTidesRequest, opts ...grpc.CallOption) (*PredictedTidesResponse, error)
}

type tidesServiceClient struct {
	cc *grpc.ClientConn
}

func NewTidesServiceClient(cc *grpc.ClientConn) TidesServiceClient {
	return &tidesServiceClient{cc}
}

func (c *tidesServiceClient) RealtimeTides(ctx context.Context, in *RealtimeTidesRequest, opts ...grpc.CallOption) (*RealtimeTidesResponse, error) {
	out := new(RealtimeTidesResponse)
	err := c.cc.Invoke(ctx, "/jimmyau.tides.TidesService/RealtimeTides", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tidesServiceClient) PredictedTides(ctx context.Context, in *PredictedTidesRequest, opts ...grpc.CallOption) (*PredictedTidesResponse, error) {
	out := new(PredictedTidesResponse)
	err := c.cc.Invoke(ctx, "/jimmyau.tides.TidesService/PredictedTides", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TidesServiceServer is the server API for TidesService service.
type TidesServiceServer interface {
	RealtimeTides(context.Context, *RealtimeTidesRequest) (*RealtimeTidesResponse, error)
	PredictedTides(context.Context, *PredictedTidesRequest) (*PredictedTidesResponse, error)
}

func RegisterTidesServiceServer(s *grpc.Server, srv TidesServiceServer) {
	s.RegisterService(&_TidesService_serviceDesc, srv)
}

func _TidesService_RealtimeTides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealtimeTidesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TidesServiceServer).RealtimeTides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jimmyau.tides.TidesService/RealtimeTides",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TidesServiceServer).RealtimeTides(ctx, req.(*RealtimeTidesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TidesService_PredictedTides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictedTidesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TidesServiceServer).PredictedTides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jimmyau.tides.TidesService/PredictedTides",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TidesServiceServer).PredictedTides(ctx, req.(*PredictedTidesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TidesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jimmyau.tides.TidesService",
	HandlerType: (*TidesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RealtimeTides",
			Handler:    _TidesService_RealtimeTides_Handler,
		},
		{
			MethodName: "PredictedTides",
			Handler:    _TidesService_PredictedTides_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tides/api.proto",
}
